version: "3.8"

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dotnet_app
    restart: always
    ports:
      - "127.0.0.1:8000:8080"
      - "100.100.56.64:8000:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs_app
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api-doctors-care.quocdk.id.vn
      - API_URL=http://backend:8080
    ports:
      - "127.0.0.1:3000:3000"
      - "100.100.56.64:3000:3000"
    depends_on:
      - backend
    command: >
      sh -c "echo 'Waiting for backend...' && 
             while ! curl -s http://backend:8080/api/specialties > /dev/null; do
               sleep 2
             done && 
             echo 'Backend is up! Starting build...' && 
             npm run build && 
             npm run start"


volumes:
  mssql_data:
