version: "3.8"

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dotnet_app
    restart: always
    ports:
      - "127.0.0.1:8000:8080"
      - "100.100.56.64:8000:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Build-time variable for client-side API requests
        NEXT_PUBLIC_API_URL: http://localhost:8000
    container_name: nextjs_app
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
      - "100.100.56.64:3000:3000"
    depends_on:
      - backend

volumes:
  mssql_data:
